# Generated by Django 4.2.7 on 2023-11-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='marque',
            field=models.ForeignKey(help_text='Marque de la voiture', on_delete=django.db.models.deletion.PROTECT, related_name='voitures', to='car_dealer.marque'),
        ),
    ]
