# Generated by Django 4.2.7 on 2023-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postal',
            field=models.IntegerField(blank=True, help_text='Code Postal', null=True),
        ),
    ]
