# Generated by Django 4.2.7 on 2023-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0002_alter_voiture_marque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image de la voiture', upload_to='images/voitures/')),
            ],
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='voiture',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Photos de la voiture', to='car_dealer.photo'),
        ),
    ]
