# Generated by Django 4.2.7 on 2023-11-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0003_photo_remove_voiture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='modele',
            field=models.ForeignKey(help_text='Modèle de la voiture', on_delete=django.db.models.deletion.CASCADE, to='car_dealer.modele'),
        ),
    ]
