# Generated by Django 4.2.7 on 2023-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0004_alter_voiture_modele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='photos',
        ),
        migrations.AddField(
            model_name='voiture',
            name='photos',
            field=models.ImageField(blank=True, help_text='Image de la voiture', null=True, upload_to='images/voitures/'),
        ),
    ]
