# Generated by Django 4.2.7 on 2023-11-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0005_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureSoumisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.BooleanField(default=False, verbose_name='Réserver')),
                ('sold', models.BooleanField(default=False, verbose_name='Vendu')),
                ('annee_fabrication', models.PositiveIntegerField(help_text='Année de fabrication')),
                ('carburant', models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Essence', 'Essence'), ('Ethanol', 'Ethanol'), ('Electrique', 'Electrique'), ('Hydrogene', 'Hydrogene'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Hybride (Elec - Ess)', 'Hybride (Elec - Ess)'), ('Hybride (Elec - Diesel)', 'Hybride (Elec - Diesel)'), ('Autres', 'Autres')], help_text='Type de carburant de la voiture', max_length=90, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique'), ('Semi-automatique', 'Semi-automatique')], help_text='Type de transmission', max_length=90, null=True)),
                ('kilometrage', models.PositiveIntegerField(help_text='Kilométrage actuel')),
                ('cruise_control', models.BooleanField(default=False, verbose_name='Cruise Control')),
                ('direction_assistee', models.BooleanField(default=False, verbose_name='Direction assistée')),
                ('audio_interface', models.BooleanField(default=False, verbose_name='Audio Interface')),
                ('airbags', models.BooleanField(default=False, verbose_name='Airbags')),
                ('air_conditionne', models.BooleanField(default=False, verbose_name='Air Conditionné')),
                ('siege_chauffant', models.BooleanField(default=False, verbose_name='Siège Chauffant')),
                ('alarm_system', models.BooleanField(default=False, verbose_name='Alarm System')),
                ('parkassist', models.BooleanField(default=False, verbose_name='Park Assist')),
                ('camera_recul', models.BooleanField(default=False, verbose_name='Camera de Recul')),
                ('start_stop', models.BooleanField(default=False, verbose_name='Start Stop')),
                ('essui_auto', models.BooleanField(default=False, verbose_name='Essuie-glace Auto')),
                ('car_play', models.BooleanField(default=False, verbose_name='Car Play-System')),
                ('description', models.TextField(blank=True, help_text='Description de la voiture', null=True)),
                ('date_poste', models.DateTimeField(auto_now_add=True, help_text="Date de publication de l'annonce")),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('car_photo_9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('prix', models.DecimalField(decimal_places=0, help_text='Prix de la voiture', max_digits=10)),
                ('marque', models.ForeignKey(help_text='Marque de la voiture', on_delete=django.db.models.deletion.PROTECT, related_name='voitures_a_lachat', to='car_dealer.marque')),
                ('modele', models.ForeignKey(help_text='Modèle de la voiture', on_delete=django.db.models.deletion.CASCADE, to='car_dealer.modele')),
            ],
            options={
                'ordering': ['-date_poste'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date de la demande')),
                ('date_desiree', models.DateTimeField(blank=True, help_text="Date desiree de l'intervention", null=True)),
                ('details', models.TextField(blank=True, help_text='Details specifique', null=True)),
                ('genre', models.CharField(blank=True, choices=[('Entretien', 'Entretien'), ('Reparation, panne', 'Reparation, panne'), ('Carrosserie', 'Carrosserie')], help_text='Type de service', max_length=90, null=True)),
                ('startLocation', models.CharField(blank=True, help_text='Commune depart', max_length=100, null=True)),
                ('endLocation', models.CharField(blank=True, help_text='Commune arrivee', max_length=100, null=True)),
                ('service', models.ForeignKey(help_text='Service selectionner', on_delete=django.db.models.deletion.CASCADE, to='car_dealer.service')),
            ],
        ),
    ]
