# Generated by Django 4.2.7 on 2023-11-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0005_remove_voiture_photos_voiture_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='cruise_control',
            field=models.BooleanField(default=False, verbose_name='Cruise Control'),
        ),
    ]
