# Generated by Django 4.2.7 on 2023-11-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0006_voituresoumisse_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='service_id',
        ),
        migrations.AddField(
            model_name='demande',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='first_name',
            field=models.CharField(blank=True, help_text='Prenom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='last_name',
            field=models.CharField(blank=True, help_text='Nom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Service selectionner', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='demande_id',
            field=models.ForeignKey(blank=True, help_text='Identifiant du Service', null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.demande'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='date_desiree',
            field=models.DateTimeField(blank=True, help_text="  (Date d'intervention souhaitée)", null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Email', max_length=100),
        ),
    ]
