# Generated by Django 4.2.7 on 2023-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0006_voiture_cruise_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='air_conditionne',
            field=models.BooleanField(default=False, verbose_name='Air Conditioninne'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='airbags',
            field=models.BooleanField(default=False, verbose_name='Airbags'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='alarm_system',
            field=models.BooleanField(default=False, verbose_name='Alarm System'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='audio_interface',
            field=models.BooleanField(default=False, verbose_name='Audio Interface'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='camera_recul',
            field=models.BooleanField(default=False, verbose_name='Camera de Recul'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='car_play',
            field=models.BooleanField(default=False, verbose_name='Car Play-System'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='direction_assistee',
            field=models.BooleanField(default=False, verbose_name='Direction assistée'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='essui_auto',
            field=models.BooleanField(default=False, verbose_name='Essui-glace Auto'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='parkassist',
            field=models.BooleanField(default=False, verbose_name='ParkAssist'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='siege_chauffant',
            field=models.BooleanField(default=False, verbose_name='Siege Chauffant'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='start_stop',
            field=models.BooleanField(default=False, verbose_name='Start Stop'),
        ),
    ]
