# Generated by Django 4.2.7 on 2023-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0007_remove_vente_service_id_demande_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='car_doc',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
