# Generated by Django 4.2.7 on 2023-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0007_voiture_air_conditionne_voiture_airbags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='carburant',
            field=models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Essence', 'Essence')], help_text='Type de carburant de la voiture (Diesel/Essence)', max_length=10, null=True),
        ),
    ]
