# Generated by Django 4.2.7 on 2023-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0008_voiture_carburant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='voiture',
            name='carburant',
            field=models.CharField(blank=True, choices=[('Diesel', 'Diesel'), ('Essence', 'Essence'), ('Ethanol', 'Ethanol'), ('Electrique', 'Electrique'), ('Hydrogene', 'Hydrogene'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Hybride (Elec - Ess)', 'Hybride (Elec - Ess)'), ('Hybride (Elec - Diesel)', 'Hybride (Elec - Diesel)'), ('Autres', 'Autres')], help_text='Type de carburant de la voiture (Diesel/Essence)', max_length=90, null=True),
        ),
    ]
