# Generated by Django 4.2.7 on 2023-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0009_alter_demande_date_desiree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voituresoumisse',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='voituresoumisse',
            name='sold',
        ),
        migrations.AddField(
            model_name='voituresoumisse',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voituresoumisse',
            name='first_name',
            field=models.CharField(blank=True, help_text='Prenom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voituresoumisse',
            name='last_name',
            field=models.CharField(blank=True, help_text='Nom', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voituresoumisse',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone', max_length=100, null=True),
        ),
    ]
