# Generated by Django 4.2.7 on 2023-12-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0010_remove_voituresoumisse_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voituresoumisse',
            name='user_id',
            field=models.ForeignKey(blank=True, help_text='Identifiant du membre qui a soumis la voiture', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
