# Generated by Django 4.2.7 on 2023-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0010_remove_voiture_photos_voiture_car_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='parkassist',
            field=models.BooleanField(default=False, verbose_name='Park Assist'),
        ),
    ]
