# Generated by Django 4.2.7 on 2023-12-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0011_voituresoumisse_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voituresoumisse',
            name='marque',
            field=models.CharField(blank=True, help_text='Marque', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voituresoumisse',
            name='modele',
            field=models.CharField(blank=True, help_text='Modele', max_length=100, null=True),
        ),
    ]
