# Generated by Django 4.2.7 on 2023-11-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0012_voiture_sold_alter_voiture_carburant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='prix',
            field=models.DecimalField(decimal_places=0, help_text='Prix de la voiture', max_digits=10),
        ),
    ]
