# Generated by Django 4.2.7 on 2023-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0012_alter_voituresoumisse_marque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='car_doc',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
