# Generated by Django 4.2.7 on 2023-11-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0013_alter_voiture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique'), ('Semi-automatique', 'Semi-qutomatique')], help_text='Type de transmission', max_length=90, null=True),
        ),
    ]
