# Generated by Django 5.0.3 on 2024-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0014_demande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('normal', 'normal'), ('client', 'client'), ('vendeur', 'vendeur')], default='normal', max_length=100),
        ),
    ]
