# Generated by Django 4.2.7 on 2023-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0014_voiture_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='reserve',
            field=models.BooleanField(default=False, verbose_name='Reserver'),
        ),
    ]
