# Generated by Django 5.0.3 on 2024-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0015_alter_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='air_conditionne',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='airbags',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='alarm_system',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='audio_interface',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='camera_recul',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_play',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='cruise_control',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='direction_assistee',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='essui_auto',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='parkassist',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='siege_chauffant',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='start_stop',
        ),
        migrations.AddField(
            model_name='voiture',
            name='status',
            field=models.CharField(choices=[('reservé', 'Reservé'), ('vendu', 'Vendu'), ('standby', 'Standby')], default='standby', help_text='Statut de la voiture', max_length=10),
        ),
        migrations.AddField(
            model_name='voiture',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='Options de la voiture', to='car_dealer.option'),
        ),
    ]
