# Generated by Django 5.0.3 on 2024-07-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0016_option_remove_voiture_air_conditionne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='options',
        ),
        migrations.AddField(
            model_name='voiture',
            name='air_conditionne',
            field=models.BooleanField(default=False, help_text='Climatisation'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='airbags',
            field=models.BooleanField(default=False, help_text='Airbags'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='alarm_system',
            field=models.BooleanField(default=False, help_text="Système d'alarme"),
        ),
        migrations.AddField(
            model_name='voiture',
            name='audio_interface',
            field=models.BooleanField(default=False, help_text='Interface audio'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='camera_recul',
            field=models.BooleanField(default=False, help_text='Caméra de recul'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='car_play',
            field=models.BooleanField(default=False, help_text='Apple CarPlay'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='cruise_control',
            field=models.BooleanField(default=False, help_text='Contrôle de croisière'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='direction_assistee',
            field=models.BooleanField(default=False, help_text='Direction assistée'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='essui_auto',
            field=models.BooleanField(default=False, help_text='Essuie-glace automatique'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='parkassist',
            field=models.BooleanField(default=False, help_text='Aide au stationnement'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='siege_chauffant',
            field=models.BooleanField(default=False, help_text='Sièges chauffants'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='start_stop',
            field=models.BooleanField(default=False, help_text='Système start/stop'),
        ),
    ]
