# Generated by Django 4.2.7 on 2023-11-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_dealer', '0016_service_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service_id',
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Identifiant du Service', null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(help_text='Nom du service', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.DecimalField(decimal_places=0, help_text='Prix du service', max_digits=10),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='air_conditionne',
            field=models.BooleanField(default=False, verbose_name='Air Conditionné'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='essui_auto',
            field=models.BooleanField(default=False, verbose_name='Essuie-glace Auto'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='reserve',
            field=models.BooleanField(default=False, verbose_name='Réserver'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='siege_chauffant',
            field=models.BooleanField(default=False, verbose_name='Siège Chauffant'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique'), ('Semi-automatique', 'Semi-automatique')], help_text='Type de transmission', max_length=90, null=True),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('Vente', 'Vente'), ('Service', 'Service')], help_text='Type de service', max_length=90, null=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date de la vente')),
                ('montant_total', models.DecimalField(blank=True, decimal_places=0, help_text='Montant total de la vente', max_digits=10, null=True)),
                ('montant_acompte', models.DecimalField(blank=True, decimal_places=0, help_text="Montant de l'acompte", max_digits=10, null=True)),
                ('service_id', models.ForeignKey(blank=True, help_text='Identifiant du Service', null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.service')),
                ('user_id', models.ForeignKey(help_text='Identifiant du User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voiture_id', models.ForeignKey(blank=True, help_text='Identifiant de la voiture', null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.voiture')),
            ],
        ),
    ]
