# Generated by Django 5.0.3 on 2024-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0017_remove_voiture_options_voiture_air_conditionne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='prix_min',
            field=models.DecimalField(decimal_places=0, default=1000, help_text='Prix minimale de vente', max_digits=10),
            preserve_default=False,
        ),
    ]
