# Generated by Django 5.0.3 on 2024-07-22 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0018_voiture_prix_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_1',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_2',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_3',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_4',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_5',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_6',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_7',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_8',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='car_photo_9',
        ),
        migrations.AddField(
            model_name='imagevoiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_dealer.voiture'),
        ),
    ]
