# Generated by Django 4.2.7 on 2023-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0018_rename_service_review_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix du service', max_digits=10, null=True),
        ),
    ]
