# Generated by Django 5.0.3 on 2024-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0019_imagevoiture_delete_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='status',
            field=models.CharField(choices=[('standby', 'Standby'), ('avendre', 'A vendre'), ('reservé', 'Reservé'), ('transit', 'transit'), ('vendu', 'Vendu')], default='standby', help_text='Statut de la voiture', max_length=10),
        ),
    ]
