# Generated by Django 4.2.7 on 2023-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0019_alter_service_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='username', max_length=100)),
                ('first_name', models.CharField(help_text='Prenom', max_length=100)),
                ('last_name', models.CharField(help_text='Nom', max_length=100)),
                ('email', models.EmailField(help_text='Nom du modèle', max_length=100)),
                ('phone', models.CharField(help_text='Phone', max_length=100)),
                ('address', models.CharField(help_text='adresse', max_length=100)),
                ('postal', models.IntegerField(help_text='Code Postal')),
                ('ville', models.CharField(help_text='Ville', max_length=100)),
            ],
        ),
    ]
