# Generated by Django 4.2.7 on 2023-11-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0020_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
