# Generated by Django 5.0.3 on 2024-09-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0021_alter_demande_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='voiture',
            field=models.ForeignKey(blank=True, help_text='Voiture', null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.voiture'),
        ),
    ]
