# Generated by Django 5.0.3 on 2024-09-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0022_demande_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='genre',
            field=models.CharField(blank=True, choices=[('Entretien', 'Entretien'), ('Reparation, panne', 'Reparation, panne'), ('Carrosserie', 'Carrosserie'), ('Deplacment', 'Deplacement'), ('Info', 'Info')], help_text='Type de service', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='voiture',
            field=models.ForeignKey(blank=True, help_text='Email', null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer.voiture'),
        ),
    ]
