# Generated by Django 5.0.3 on 2024-09-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0023_alter_demande_genre_alter_demande_voiture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='status',
            field=models.CharField(blank=True, choices=[('Actif', 'Actif'), ('En preparation', 'En preparation'), ('Close', 'Close')], default='Actif', help_text='Type de service', max_length=90, null=True),
        ),
    ]
