# Generated by Django 5.0.3 on 2024-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0024_alter_demande_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='genre',
            field=models.CharField(blank=True, choices=[('Entretien', 'Entretien'), ('Reparation, panne', 'Reparation, panne'), ('Carrosserie', 'Carrosserie'), ('Deplacement', 'Deplacement'), ('Info', 'Info')], help_text='Type de service', max_length=90, null=True),
        ),
    ]
