# Generated by Django 5.1.1 on 2024-09-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0025_alter_demande_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Montant restant à payer', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='paid',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('partially', 'Partiellement')], default='no', max_length=10, verbose_name='Payé'),
        ),
    ]
