# Generated by Django 5.1.1 on 2024-09-27 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0026_option_vente_montant_restant_alter_vente_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='voitures_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
