# Generated by Django 5.1.1 on 2024-09-29 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0031_alter_notes_demande_id_alter_notes_vente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date de la demande'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='status',
            field=models.CharField(choices=[('standby', 'Standby'), ('avendre', 'A vendre'), ('ready', 'Ready'), ('reservé', 'Reservé'), ('transit', 'transit'), ('vendu', 'Vendu'), ('livré', 'Livré')], default='standby', help_text='Statut de la voiture', max_length=10),
        ),
    ]
