# Generated by Django 5.1.1 on 2024-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0036_voiture_num_chassis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='status',
            field=models.CharField(choices=[('standby', 'Standby'), ('Available', 'Available'), ('reservé', 'Reservé'), ('ready', 'Ready'), ('vendu', 'Vendu'), ('livré', 'Livré')], default='standby', help_text='Statut de la voiture', max_length=10),
        ),
    ]
