# Generated by Django 5.1.1 on 2024-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0037_alter_voiture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='paid',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('partially', 'Partiellement'), ('cancelled', 'Cancelled')], default='no', max_length=10, verbose_name='Payé'),
        ),
    ]
